version: "3.5"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - backend/.env
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./backend
    container_name: api
    image: api
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - ./backend:/app/
      - /app/node_modules
    depends_on:
      - db
