version: '3.5'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: ./backend
    container_name: api
    image: api
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/db
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/
      - /app/node_modules
    depends_on:
      - db
