version: '3.5'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - backend/.env
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
