version: "3.5"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - ./backend/.env
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./backend
    container_name: backend
    image: backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
      - "5555:5555"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # client:
  #   depends_on: app
  #   build: ./frontend
  #   container_name: frontend
  #   image: frontend
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "3000:8000"
  #   volumes:
  #     - ./frontend:/client
